# Generated by Django 2.1.5 on 2019-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('photo', models.URLField()),
                ('data', models.DateField()),
            ],
        ),
    ]
